name: 'Setup Environment'
description: 'Common setup steps for Unity release workflows (Git config and environment prep)'

inputs:
  gh_token:
    description: 'GitHub token for gh CLI authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Prepare Environment
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y gh jq || true
        gh auth status || gh auth login --with-token <<< "$GH_TOKEN"

